In [6]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [7]:
df = pd.read_csv('Advertising.csv')

In [8]:
X = df.drop('sales', axis=1)

In [9]:
y = df['sales']

In [10]:
from sklearn.preprocessing import PolynomialFeatures

In [11]:
polynomial_converter = PolynomialFeatures(degree=3,include_bias=False)

In [12]:
poly_features = polynomial_converter.fit_transform(X)

In [13]:
poly_features.shape

(200, 19)

In [14]:
from sklearn.model_selection import train_test_split

In [15]:
 X_train, X_test, y_train, y_test = train_test_split(poly_features, y, test_size=0.3, random_state=101)

In [16]:
X_train.shape

(140, 19)

In [17]:
from sklearn.preprocessing import StandardScaler

In [18]:
scaler = StandardScaler()

In [19]:
scaler.fit(X_train)

StandardScaler()

In [20]:
X_train = scaler.transform(X_train)

In [21]:
X_test = scaler.transform(X_test)

In [22]:
X_train[0]

array([ 0.49300171, -0.33994238,  1.61586707,  0.28407363, -0.02568776,
        1.49677566, -0.59023161,  0.41659155,  1.6137853 ,  0.08057172,
       -0.05392229,  1.01524393, -0.36986163,  0.52457967,  1.48737034,
       -0.66096022, -0.16360242,  0.54694754,  1.37075536])

In [23]:
from sklearn.linear_model import Ridge

In [24]:
ridge_model = Ridge(alpha=10)

In [25]:
ridge_model.fit(X_train,y_train)

Ridge(alpha=10)

In [26]:
test_predictions = ridge_model.predict(X_test)

In [27]:
from sklearn.metrics import mean_absolute_error, mean_squared_error

In [28]:
MAE= mean_absolute_error(y_test,test_predictions)

In [29]:
MAE

0.5774404204714169

In [30]:
RMSE = np.sqrt(mean_squared_error(y_test,test_predictions))

In [31]:
RMSE

0.8946386461319674

In [32]:
from sklearn.linear_model import RidgeCV

In [40]:
ridge_cv_model = RidgeCV(alphas=(0.1,1.0,10.0), scoring='neg_mean_absolute_error')

In [41]:
ridge_cv_model.fit(X_train,y_train)

RidgeCV(scoring='neg_mean_absolute_error')

In [42]:
ridge_cv_model.alpha_

0.1

In [43]:
from sklearn.metrics._scorer import _SCORERS

In [44]:
_SCORERS.keys()

dict_keys(['explained_variance', 'r2', 'max_error', 'matthews_corrcoef', 'neg_median_absolute_error', 'neg_mean_absolute_error', 'neg_mean_absolute_percentage_error', 'neg_mean_squared_error', 'neg_mean_squared_log_error', 'neg_root_mean_squared_error', 'neg_mean_poisson_deviance', 'neg_mean_gamma_deviance', 'accuracy', 'top_k_accuracy', 'roc_auc', 'roc_auc_ovr', 'roc_auc_ovo', 'roc_auc_ovr_weighted', 'roc_auc_ovo_weighted', 'balanced_accuracy', 'average_precision', 'neg_log_loss', 'neg_brier_score', 'positive_likelihood_ratio', 'neg_negative_likelihood_ratio', 'adjusted_rand_score', 'rand_score', 'homogeneity_score', 'completeness_score', 'v_measure_score', 'mutual_info_score', 'adjusted_mutual_info_score', 'normalized_mutual_info_score', 'fowlkes_mallows_score', 'precision', 'precision_macro', 'precision_micro', 'precision_samples', 'precision_weighted', 'recall', 'recall_macro', 'recall_micro', 'recall_samples', 'recall_weighted', 'f1', 'f1_macro', 'f1_micro', 'f1_samples', 'f1_weig

In [45]:
test_predictions = ridge_cv_model.predict(X_test)

In [46]:
MAE= mean_absolute_error(y_test,test_predictions)

In [47]:
RMSE = np.sqrt(mean_squared_error(y_test,test_predictions))

In [48]:
MAE

0.4273774884348172

In [49]:
RMSE

0.6180719926963456

In [50]:
ridge_cv_model.coef_

array([ 5.40769392,  0.5885865 ,  0.40390395, -6.18263924,  4.59607939,
       -1.18789654, -1.15200458,  0.57837796, -0.1261586 ,  2.5569777 ,
       -1.38900471,  0.86059434,  0.72219553, -0.26129256,  0.17870787,
        0.44353612, -0.21362436, -0.04622473, -0.06441449])

In [52]:
from sklearn.linear_model import LassoCV

In [111]:
lasso_cv_model = LassoCV(eps=0.001, n_alphas=100,cv=5,max_iter=1000000)

In [112]:
lasso_cv_model.fit(X_train,y_train)

LassoCV(cv=5, max_iter=1000000)

In [113]:
lasso_cv_model.alpha_

0.004943070909225828

In [114]:
test_predictions = lasso_cv_model.predict(X_test)

In [115]:
MAE= mean_absolute_error(y_test,test_predictions)

In [116]:
RMSE = np.sqrt(mean_squared_error(y_test,test_predictions))

In [117]:
MAE

0.43350346185900734

In [118]:
RMSE

0.6063140748984037

In [119]:
lasso_cv_model.coef_

array([ 4.86023329,  0.12544598,  0.20746872, -4.99250395,  4.38026519,
       -0.22977201, -0.        ,  0.07267717, -0.        ,  1.77780246,
       -0.69614918, -0.        ,  0.12044132, -0.        , -0.        ,
       -0.        ,  0.        ,  0.        , -0.        ])

In [120]:
from sklearn.linear_model import ElasticNetCV

In [123]:
elastic_model = ElasticNetCV(l1_ratio=[.1,.5,.7,.9,.95,.99,1], eps=0.001, n_alphas=100, max_iter=1000000)

In [124]:
elastic_model.fit(X_train,y_train)

ElasticNetCV(l1_ratio=[0.1, 0.5, 0.7, 0.9, 0.95, 0.99, 1], max_iter=1000000)

In [125]:
elastic_model.l1_ratio

[0.1, 0.5, 0.7, 0.9, 0.95, 0.99, 1]

In [126]:
elastic_model.l1_ratio_

1.0

In [127]:
elastic_model.alpha_

0.004943070909225828

In [128]:
lasso_cv_model.alpha_

0.004943070909225828

In [129]:
test_predictions = elastic_model.predict(X_test)

In [130]:
MAE= mean_absolute_error(y_test,test_predictions)

In [131]:
RMSE = np.sqrt(mean_squared_error(y_test,test_predictions))

In [132]:
MAE

0.43350346185900734

In [133]:
RMSE

0.6063140748984037