In [3]:
import numpy as np

In [5]:
mylist = [1,2,3]

In [6]:
type(mylist)

list

In [8]:
np.array(mylist)

array([1, 2, 3])

In [10]:
mylist

[1, 2, 3]

In [12]:
myarr = np.array(mylist)

In [13]:
myarr

array([1, 2, 3])

In [14]:
type(myarr)

numpy.ndarray

In [15]:
my_matrix = [[1,2,3],[4,5,6],[7,8,9]]
my_matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [16]:
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [20]:
np.arange(0,101,20)

array([  0,  20,  40,  60,  80, 100])

In [21]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [23]:
np.zeros((2,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [26]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [31]:
len(np.linspace(0,5,21))

21

In [33]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [48]:
np.random.rand(5,2)

array([[0.9465611 , 0.23179146],
       [0.19872203, 0.15887088],
       [0.51070577, 0.76657804],
       [0.66502702, 0.94400626],
       [0.10657968, 0.99997137]])

In [49]:
np.random.randn(10)

array([ 0.53667349,  0.64417676,  0.54405885, -0.8281482 ,  0.16277876,
        0.22674723, -0.15915328,  0.29481698,  1.19342766,  2.23743133])

In [50]:
np.random.randn(2,3)

array([[ 0.10658443,  0.42958528, -0.23979026],
       [ 0.24386784,  1.63318134, -0.89505302]])

In [53]:
np.random.randint(0,101,10)

array([85, 88, 67, 52, 85, 67, 61, 99, 24, 79])

In [55]:
np.random.seed(101)
np.random.rand(4)

array([0.51639863, 0.57066759, 0.02847423, 0.17152166])

In [56]:
np.random.seed(101)
np.random.rand(4)

array([0.51639863, 0.57066759, 0.02847423, 0.17152166])

In [57]:
np.random.rand(4)

array([0.68527698, 0.83389686, 0.30696622, 0.89361308])

In [58]:
np.random.rand(4)


array([0.72154386, 0.18993895, 0.55422759, 0.35213195])

In [59]:
np.random.seed(101)
np.random.rand(4)


array([0.51639863, 0.57066759, 0.02847423, 0.17152166])

In [83]:
arr = np.arange(0,25)

In [62]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [66]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [67]:
ranarr = np.random.randint(0,101,10)

In [68]:
ranarr

array([ 9, 77, 40,  4, 63, 40, 60, 92, 64,  5])

In [70]:
ranarr.max()

92

In [72]:
ranarr.min()

4

In [73]:
ranarr.argmax()

7

In [74]:
ranarr.argmin()

3

In [75]:
ranarr.dtype


dtype('int32')

In [84]:
arr


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [85]:
arr.shape


(25,)

In [86]:
arr = arr.reshape(5,5)

In [87]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [88]:
arr.shape

(5, 5)

In [89]:
arr.reshape(25,1)


array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24]])

In [90]:
arr.reshape(1,25)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24]])